export const SITE_TITLE = 'TravelScope';
export const SITE_DESCRIPTION = 'Your ultimate travel guide to cities around the world. Discover things to do, where to eat, where to stay, and practical tips for 200+ destinations.';
export const SITE_URL = 'https://yourdomain.com';

export const CATEGORIES = [
  { id: 'Essentials', label: 'Essentials', icon: '📋' },
  { id: 'Things to Do', label: 'Things to Do', icon: '🎯' },
  { id: 'Experiences & Activities', label: 'Experiences', icon: '🎢' },
  { id: 'Attractions', label: 'Attractions', icon: '🏛️' },
  { id: 'Itineraries', label: 'Itineraries', icon: '🗓️' },
  { id: 'Food & Dining', label: 'Food & Dining', icon: '🍽️' },
  { id: 'Shopping', label: 'Shopping', icon: '🛍️' },
  { id: 'Transport', label: 'Transport', icon: '🚇' },
  { id: 'Special Guides', label: 'Special Guides', icon: '⭐' },
  { id: 'Seasonal & Monthly', label: 'Seasonal', icon: '🌤️' },
  { id: 'Hotels & Accommodation', label: 'Hotels', icon: '🏨' },
  { id: 'Practical Information', label: 'Practical Info', icon: 'ℹ️' },
  { id: 'Visa & Entry', label: 'Visa & Entry', icon: '🛂' },
  { id: 'Money & Payments', label: 'Money', icon: '💰' },
  { id: 'Booking & Experiences', label: 'Booking', icon: '🎟️' },
  { id: 'Yacht & Cruise', label: 'Yacht & Cruise', icon: '🚢' },
  { id: 'Activities Planning', label: 'Activities', icon: '🏄' },
  { id: 'Holiday Packages', label: 'Packages', icon: '📦' },
  { id: 'Trust & Conversion', label: 'Tips & Trust', icon: '✅' },
  { id: 'Comparisons', label: 'Comparisons', icon: '⚖️' },
] as const;

export const CITIES: Record<string, { name: string; country: string; slug: string }> = {
  dubai: { name: 'Dubai', country: 'United Arab Emirates', slug: 'dubai' },
  abudhabi: { name: 'Abu Dhabi', country: 'United Arab Emirates', slug: 'abu-dhabi' },
  doha: { name: 'Doha', country: 'Qatar', slug: 'doha' },
  muscat: { name: 'Muscat', country: 'Oman', slug: 'muscat' },
  riyadh: { name: 'Riyadh', country: 'Saudi Arabia', slug: 'riyadh' },
  jeddah: { name: 'Jeddah', country: 'Saudi Arabia', slug: 'jeddah' },
  amman: { name: 'Amman', country: 'Jordan', slug: 'amman' },
  beirut: { name: 'Beirut', country: 'Lebanon', slug: 'beirut' },
  telaviv: { name: 'Tel Aviv', country: 'Israel', slug: 'tel-aviv' },
  jerusalem: { name: 'Jerusalem', country: 'Israel', slug: 'jerusalem' },
  mumbai: { name: 'Mumbai', country: 'India', slug: 'mumbai' },
  delhi: { name: 'Delhi', country: 'India', slug: 'delhi' },
  goa: { name: 'Goa', country: 'India', slug: 'goa' },
  jaipur: { name: 'Jaipur', country: 'India', slug: 'jaipur' },
  bangalore: { name: 'Bangalore', country: 'India', slug: 'bangalore' },
  colombo: { name: 'Colombo', country: 'Sri Lanka', slug: 'colombo' },
  kathmandu: { name: 'Kathmandu', country: 'Nepal', slug: 'kathmandu' },
  maldives: { name: 'Maldives', country: 'Maldives', slug: 'maldives' },
  dhaka: { name: 'Dhaka', country: 'Bangladesh', slug: 'dhaka' },
  bangkok: { name: 'Bangkok', country: 'Thailand', slug: 'bangkok' },
  phuket: { name: 'Phuket', country: 'Thailand', slug: 'phuket' },
  chiangmai: { name: 'Chiang Mai', country: 'Thailand', slug: 'chiang-mai' },
  singapore: { name: 'Singapore', country: 'Singapore', slug: 'singapore' },
  kualalumpur: { name: 'Kuala Lumpur', country: 'Malaysia', slug: 'kuala-lumpur' },
  langkawi: { name: 'Langkawi', country: 'Malaysia', slug: 'langkawi' },
  bali: { name: 'Bali', country: 'Indonesia', slug: 'bali' },
  jakarta: { name: 'Jakarta', country: 'Indonesia', slug: 'jakarta' },
  hanoi: { name: 'Hanoi', country: 'Vietnam', slug: 'hanoi' },
  hochiminhcity: { name: 'Ho Chi Minh City', country: 'Vietnam', slug: 'ho-chi-minh-city' },
  manila: { name: 'Manila', country: 'Philippines', slug: 'manila' },
  cebu: { name: 'Cebu', country: 'Philippines', slug: 'cebu' },
  phnompenh: { name: 'Phnom Penh', country: 'Cambodia', slug: 'phnom-penh' },
  siemreap: { name: 'Siem Reap', country: 'Cambodia', slug: 'siem-reap' },
  yangon: { name: 'Yangon', country: 'Myanmar', slug: 'yangon' },
  luangprabang: { name: 'Luang Prabang', country: 'Laos', slug: 'luang-prabang' },
  tokyo: { name: 'Tokyo', country: 'Japan', slug: 'tokyo' },
  kyoto: { name: 'Kyoto', country: 'Japan', slug: 'kyoto' },
  osaka: { name: 'Osaka', country: 'Japan', slug: 'osaka' },
  seoul: { name: 'Seoul', country: 'South Korea', slug: 'seoul' },
  busan: { name: 'Busan', country: 'South Korea', slug: 'busan' },
  hongkong: { name: 'Hong Kong', country: 'China', slug: 'hong-kong' },
  macau: { name: 'Macau', country: 'China', slug: 'macau' },
  shanghai: { name: 'Shanghai', country: 'China', slug: 'shanghai' },
  beijing: { name: 'Beijing', country: 'China', slug: 'beijing' },
  taipei: { name: 'Taipei', country: 'Taiwan', slug: 'taipei' },
  london: { name: 'London', country: 'United Kingdom', slug: 'london' },
  paris: { name: 'Paris', country: 'France', slug: 'paris' },
  nice: { name: 'Nice', country: 'France', slug: 'nice' },
  amsterdam: { name: 'Amsterdam', country: 'Netherlands', slug: 'amsterdam' },
  brussels: { name: 'Brussels', country: 'Belgium', slug: 'brussels' },
  berlin: { name: 'Berlin', country: 'Germany', slug: 'berlin' },
  munich: { name: 'Munich', country: 'Germany', slug: 'munich' },
  frankfurt: { name: 'Frankfurt', country: 'Germany', slug: 'frankfurt' },
  zurich: { name: 'Zurich', country: 'Switzerland', slug: 'zurich' },
  geneva: { name: 'Geneva', country: 'Switzerland', slug: 'geneva' },
  vienna: { name: 'Vienna', country: 'Austria', slug: 'vienna' },
  salzburg: { name: 'Salzburg', country: 'Austria', slug: 'salzburg' },
  rome: { name: 'Rome', country: 'Italy', slug: 'rome' },
  florence: { name: 'Florence', country: 'Italy', slug: 'florence' },
  venice: { name: 'Venice', country: 'Italy', slug: 'venice' },
  milan: { name: 'Milan', country: 'Italy', slug: 'milan' },
  naples: { name: 'Naples', country: 'Italy', slug: 'naples' },
  amalficoast: { name: 'Amalfi Coast', country: 'Italy', slug: 'amalfi-coast' },
  barcelona: { name: 'Barcelona', country: 'Spain', slug: 'barcelona' },
  madrid: { name: 'Madrid', country: 'Spain', slug: 'madrid' },
  seville: { name: 'Seville', country: 'Spain', slug: 'seville' },
  ibiza: { name: 'Ibiza', country: 'Spain', slug: 'ibiza' },
  lisbon: { name: 'Lisbon', country: 'Portugal', slug: 'lisbon' },
  porto: { name: 'Porto', country: 'Portugal', slug: 'porto' },
  athens: { name: 'Athens', country: 'Greece', slug: 'athens' },
  santorini: { name: 'Santorini', country: 'Greece', slug: 'santorini' },
  mykonos: { name: 'Mykonos', country: 'Greece', slug: 'mykonos' },
  crete: { name: 'Crete', country: 'Greece', slug: 'crete' },
  dubrovnik: { name: 'Dubrovnik', country: 'Croatia', slug: 'dubrovnik' },
  split: { name: 'Split', country: 'Croatia', slug: 'split' },
  istanbul: { name: 'Istanbul', country: 'Turkey', slug: 'istanbul' },
  cappadocia: { name: 'Cappadocia', country: 'Turkey', slug: 'cappadocia' },
  antalya: { name: 'Antalya', country: 'Turkey', slug: 'antalya' },
  prague: { name: 'Prague', country: 'Czech Republic', slug: 'prague' },
  budapest: { name: 'Budapest', country: 'Hungary', slug: 'budapest' },
  warsaw: { name: 'Warsaw', country: 'Poland', slug: 'warsaw' },
  krakow: { name: 'Krakow', country: 'Poland', slug: 'krakow' },
  bucharest: { name: 'Bucharest', country: 'Romania', slug: 'bucharest' },
  moscow: { name: 'Moscow', country: 'Russia', slug: 'moscow' },
  stpetersburg: { name: 'St. Petersburg', country: 'Russia', slug: 'st-petersburg' },
  copenhagen: { name: 'Copenhagen', country: 'Denmark', slug: 'copenhagen' },
  stockholm: { name: 'Stockholm', country: 'Sweden', slug: 'stockholm' },
  oslo: { name: 'Oslo', country: 'Norway', slug: 'oslo' },
  helsinki: { name: 'Helsinki', country: 'Finland', slug: 'helsinki' },
  reykjavik: { name: 'Reykjavik', country: 'Iceland', slug: 'reykjavik' },
  edinburgh: { name: 'Edinburgh', country: 'United Kingdom', slug: 'edinburgh' },
  dublin: { name: 'Dublin', country: 'Ireland', slug: 'dublin' },
  newyork: { name: 'New York', country: 'United States', slug: 'new-york' },
  losangeles: { name: 'Los Angeles', country: 'United States', slug: 'los-angeles' },
  sanfrancisco: { name: 'San Francisco', country: 'United States', slug: 'san-francisco' },
  lasvegas: { name: 'Las Vegas', country: 'United States', slug: 'las-vegas' },
  miami: { name: 'Miami', country: 'United States', slug: 'miami' },
  orlando: { name: 'Orlando', country: 'United States', slug: 'orlando' },
  chicago: { name: 'Chicago', country: 'United States', slug: 'chicago' },
  washingtondc: { name: 'Washington D.C.', country: 'United States', slug: 'washington-dc' },
  boston: { name: 'Boston', country: 'United States', slug: 'boston' },
  hawaii: { name: 'Hawaii', country: 'United States', slug: 'hawaii' },
  neworleans: { name: 'New Orleans', country: 'United States', slug: 'new-orleans' },
  nashville: { name: 'Nashville', country: 'United States', slug: 'nashville' },
  seattle: { name: 'Seattle', country: 'United States', slug: 'seattle' },
  sandiego: { name: 'San Diego', country: 'United States', slug: 'san-diego' },
  toronto: { name: 'Toronto', country: 'Canada', slug: 'toronto' },
  vancouver: { name: 'Vancouver', country: 'Canada', slug: 'vancouver' },
  montreal: { name: 'Montreal', country: 'Canada', slug: 'montreal' },
  mexicocity: { name: 'Mexico City', country: 'Mexico', slug: 'mexico-city' },
  cancun: { name: 'Cancun', country: 'Mexico', slug: 'cancun' },
  playadelcarmen: { name: 'Playa del Carmen', country: 'Mexico', slug: 'playa-del-carmen' },
  havana: { name: 'Havana', country: 'Cuba', slug: 'havana' },
  sanjosecostarica: { name: 'San José', country: 'Costa Rica', slug: 'san-jose-costa-rica' },
  panamacity: { name: 'Panama City', country: 'Panama', slug: 'panama-city' },
  puntacana: { name: 'Punta Cana', country: 'Dominican Republic', slug: 'punta-cana' },
  jamaica: { name: 'Jamaica', country: 'Jamaica', slug: 'jamaica' },
  riodejaneiro: { name: 'Rio de Janeiro', country: 'Brazil', slug: 'rio-de-janeiro' },
  saopaulo: { name: 'São Paulo', country: 'Brazil', slug: 'sao-paulo' },
  buenosaires: { name: 'Buenos Aires', country: 'Argentina', slug: 'buenos-aires' },
  lima: { name: 'Lima', country: 'Peru', slug: 'lima' },
  cusco: { name: 'Cusco', country: 'Peru', slug: 'cusco' },
  bogota: { name: 'Bogotá', country: 'Colombia', slug: 'bogota' },
  medellin: { name: 'Medellín', country: 'Colombia', slug: 'medellin' },
  cartagena: { name: 'Cartagena', country: 'Colombia', slug: 'cartagena' },
  santiago: { name: 'Santiago', country: 'Chile', slug: 'santiago' },
  quito: { name: 'Quito', country: 'Ecuador', slug: 'quito' },
  montevideo: { name: 'Montevideo', country: 'Uruguay', slug: 'montevideo' },
  capetown: { name: 'Cape Town', country: 'South Africa', slug: 'cape-town' },
  johannesburg: { name: 'Johannesburg', country: 'South Africa', slug: 'johannesburg' },
  marrakech: { name: 'Marrakech', country: 'Morocco', slug: 'marrakech' },
  fes: { name: 'Fes', country: 'Morocco', slug: 'fes' },
  cairo: { name: 'Cairo', country: 'Egypt', slug: 'cairo' },
  luxor: { name: 'Luxor', country: 'Egypt', slug: 'luxor' },
  nairobi: { name: 'Nairobi', country: 'Kenya', slug: 'nairobi' },
  zanzibar: { name: 'Zanzibar', country: 'Tanzania', slug: 'zanzibar' },
  daressalaam: { name: 'Dar es Salaam', country: 'Tanzania', slug: 'dar-es-salaam' },
  accra: { name: 'Accra', country: 'Ghana', slug: 'accra' },
  lagos: { name: 'Lagos', country: 'Nigeria', slug: 'lagos' },
  addisababa: { name: 'Addis Ababa', country: 'Ethiopia', slug: 'addis-ababa' },
  victoriafalls: { name: 'Victoria Falls', country: 'Zimbabwe', slug: 'victoria-falls' },
  mauritius: { name: 'Mauritius', country: 'Mauritius', slug: 'mauritius' },
  seychelles: { name: 'Seychelles', country: 'Seychelles', slug: 'seychelles' },
  kigali: { name: 'Kigali', country: 'Rwanda', slug: 'kigali' },
  sydney: { name: 'Sydney', country: 'Australia', slug: 'sydney' },
  melbourne: { name: 'Melbourne', country: 'Australia', slug: 'melbourne' },
  goldcoast: { name: 'Gold Coast', country: 'Australia', slug: 'gold-coast' },
  auckland: { name: 'Auckland', country: 'New Zealand', slug: 'auckland' },
  queenstown: { name: 'Queenstown', country: 'New Zealand', slug: 'queenstown' },
  fiji: { name: 'Fiji', country: 'Fiji', slug: 'fiji' },
  borabora: { name: 'Bora Bora', country: 'French Polynesia', slug: 'bora-bora' },
  petra: { name: 'Petra', country: 'Jordan', slug: 'petra' },
  agra: { name: 'Agra', country: 'India', slug: 'agra' },
  udaipur: { name: 'Udaipur', country: 'India', slug: 'udaipur' },
  kerala: { name: 'Kerala', country: 'India', slug: 'kerala' },
  varanasi: { name: 'Varanasi', country: 'India', slug: 'varanasi' },
  kolkata: { name: 'Kolkata', country: 'India', slug: 'kolkata' },
  hyderabad: { name: 'Hyderabad', country: 'India', slug: 'hyderabad' },
  penang: { name: 'Penang', country: 'Malaysia', slug: 'penang' },
  krabi: { name: 'Krabi', country: 'Thailand', slug: 'krabi' },
  kohsamui: { name: 'Koh Samui', country: 'Thailand', slug: 'koh-samui' },
  danang: { name: 'Da Nang', country: 'Vietnam', slug: 'da-nang' },
  hiroshima: { name: 'Hiroshima', country: 'Japan', slug: 'hiroshima' },
  tulum: { name: 'Tulum', country: 'Mexico', slug: 'tulum' },
  oaxaca: { name: 'Oaxaca', country: 'Mexico', slug: 'oaxaca' },
  medina: { name: 'Medina', country: 'Saudi Arabia', slug: 'medina' },
  tbilisi: { name: 'Tbilisi', country: 'Georgia', slug: 'tbilisi' },
  baku: { name: 'Baku', country: 'Azerbaijan', slug: 'baku' },
  marrakesh: { name: 'Marrakesh', country: 'Morocco', slug: 'marrakesh' },
  casablanca: { name: 'Casablanca', country: 'Morocco', slug: 'casablanca' },
  tunis: { name: 'Tunis', country: 'Tunisia', slug: 'tunis' },
  bruges: { name: 'Bruges', country: 'Belgium', slug: 'bruges' },
  monaco: { name: 'Monaco', country: 'Monaco', slug: 'monaco' },
  malta: { name: 'Malta', country: 'Malta', slug: 'malta' },
  tallinn: { name: 'Tallinn', country: 'Estonia', slug: 'tallinn' },
  riga: { name: 'Riga', country: 'Latvia', slug: 'riga' },
  vilnius: { name: 'Vilnius', country: 'Lithuania', slug: 'vilnius' },
  belgrade: { name: 'Belgrade', country: 'Serbia', slug: 'belgrade' },
  sofia: { name: 'Sofia', country: 'Bulgaria', slug: 'sofia' },
  ljubljana: { name: 'Ljubljana', country: 'Slovenia', slug: 'ljubljana' },
  kotor: { name: 'Kotor', country: 'Montenegro', slug: 'kotor' },
  bratislava: { name: 'Bratislava', country: 'Slovakia', slug: 'bratislava' },
  portoalegre: { name: 'Porto Alegre', country: 'Brazil', slug: 'porto-alegre' },
  aswan: { name: 'Aswan', country: 'Egypt', slug: 'aswan' },
  pondicherry: { name: 'Pondicherry', country: 'India', slug: 'pondicherry' },
  lehladakh: { name: 'Leh Ladakh', country: 'India', slug: 'leh-ladakh' },
  shimla: { name: 'Shimla', country: 'India', slug: 'shimla' },
  manali: { name: 'Manali', country: 'India', slug: 'manali' },
  rishikesh: { name: 'Rishikesh', country: 'India', slug: 'rishikesh' },
  andamanislands: { name: 'Andaman Islands', country: 'India', slug: 'andaman-islands' },
  ooty: { name: 'Ooty', country: 'India', slug: 'ooty' },
  zanzibarcity: { name: 'Zanzibar City', country: 'Tanzania', slug: 'zanzibar-city' },
  chefchaouen: { name: 'Chefchaouen', country: 'Morocco', slug: 'chefchaouen' },
  essaouira: { name: 'Essaouira', country: 'Morocco', slug: 'essaouira' },
};

export const POSTS_PER_PAGE = 12;
